CREATE TABLE FAMILLE(
  FAMCode INTEGER PRIAMRY KEY,
  FAMLibelle VARCHAR2(255)
);


CREATE TABLE CATEGORIE(
  CATCode INTEGER PRIMARY KEY,
  CATLibelle VARCHAR2(255),
  CATFamCode INTEGER FOREIGN KEY REFERENCES FAMILLE(FAMCode)
);

CREATE TABLE SOUSCATEGORIE(
  SOUSCATCode INTEGER PRIMARY KEY,
  SOUCATLibelle VARCHAR2(255) NOT NULL,
  SOUSCATCatCode INTEGER FOREIGN KEY REFERENCES CATEGORIE(CATCode)
);

CREATE TABLE MARQUE(
  MARQCode INTEGER PRIMARY KEY,
  MARQNomComplet VARCHAR2(255),
  MARQNomAbrege VARCHAR2(200)
);

CREATE TABLE POSSEDER(
  POSSProdCode INTEGER PRIMARY KEY,
  POSSCaractCode INTEGER PRIMARY KEY,
  POSSProdCode INTEGER FOREIGN KEY REFERENCES PRODUIT(PRODCode),
  POSSCaractCode INTEGER FOREIGN KEY REFERENCES CARACTERISTIQUE(CARACTCode)
);

CREATE TABLE PRODUIT(
  PRODCode INTEGER PRIMARY KEY,
  PRODRef VARCHAR2(200),
  PRODDescriptif TEXT,
  PRODPrix INTEGER,
  PRODDisponibilite BOOLEAN,
  PRODMarqCode INTEGER FOREIGN KEY REFERENCES MARQUE(MARQCode),
  PRODSousCatCode INTEGER FOREIGN KEY REFERENCES SOUSCATEGORIE(SOUSCATCode)
);

CREATE TABLE CARACTERISTIQUE(
  CARACTCode INTEGER PRIMARY KEY,
  CARACTPiece VARCHAR2(255),
  CARACTLibelle VARCHAR2(255),
  CARACTDetail VARCHAR2(255)
);
